version: '3'
services:
  envoy:
    image: envoyproxy/envoy:dev-a5b712511d2b470b02f54d4be43e8b9e5647d5d6
    ports:
      - "8088:8088"
      - "9090:9090"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml