name: CI

on:
  push:
    branches:
      - main
      - demo/*
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

      # maybe adjust this setup for Kotlin specifically
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build
        run: ./gradlew build -x test
        working-directory: ./tic-tac-toe-back

  backend-unit-tests:
    name: Backend Unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

      # maybe adjust this setup for Kotlin specifically
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit tests
        run: ./gradlew test
        working-directory: ./tic-tac-toe-back

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./tic-tac-toe-web

      - name: Build Web
        run: npm run build
        working-directory: ./tic-tac-toe-web
